--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Difz25/CalculatorUI
build-by-default: true
branches:
- master
projects:
  CalculatorUI:
    path: ""
    libs:
    - src: jojoe77777/FormAPI/libFormAPI
      version: ^1.3
    icon: logo.png
...
